マージリクエストをお送りいたします。
shingoKawashim/e-navigator pull request #1
Opened 2018-06-03 07:27 UTC by shingoKawashim

やりたかったこと
---
- ユーザー登録、ログイン機能の追加
- ログインユーザー自身のプロフィールのみ編集・削除できる機能の追加
- ユーザー一覧画面の追加
- 今後の汎用性を持てるようにベース機能を構築

やったこと
----
- ベース機能をmaster_controller, view/master, base_decoratorで作成
- session_controllerでログイン機能を実装
- 削除はデータベースからレコードが削除されないようにdeletedカラムを追加

動作確認方法
---
- [ ] ユーザーを新規で作成する
- [ ] ユーザーの一覧ページにいく

その他
---

2018-06-05 07:46 UTC, pokotyamu commented
見ます 👀

2018-06-05 07:49 UTC, pokotyamu commented
まず、 Github の使い方ですが

`マージリクエストをお送りいたします。` と書いてある部分。
ここには、このプルリクエストで何がしたかったのか？ということを書きます。
なので、今回の場合でしたら、ユーザー認証機能

2018-06-05 07:53 UTC, pokotyamu commented
`.idea/.generators` など `.idea` がうまく無視されていないような気がします 🤔

2018-06-05 08:07 UTC, pokotyamu requested changes
MasterController という実装方針にちょっと違和感を感じました。
UsersController < ApplicationController とせずに、似た処理をする Controller がない状態で、この実装方式を取った理由を教えてほしいです 🙏 
(このページを参考にしたからというのでも大丈夫です)

2018-06-05 08:07 UTC, pokotyamu commented on .gitignore
> +.idea
これ、このプロジェクト以外でも適応させる意味も込めて
.gitignore_global  に書いておくと良いですよ 👍

2018-06-05 08:07 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +class MasterController < ApplicationController
ふむ。なるほど
MasterController を継承して、 UserController でも使えるようにという感じでやったんですね〜 👍 

アイディアとしては良さそうですが、若干のオーバースペックさを持っているコードになっていないかが心配ですね。
継承はすべてのメソッドを使えるようにしてしまうということも言えます。
なので、例えば SessionsController に不要な index メソッドが生えてしまったりしますよね。

他の人からみたら、「あれ index 必要なんだっけ？」という気持ちになってしまって無駄な実装な感じに見えました。
本当に必要になってから、最小単位で継承を使うというやり方のほうが良いと思います！

2018-06-05 08:07 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +class MasterController < ApplicationController
ちなみに、この実装って何か参考にされたんですか？ 😄

2018-06-05 08:07 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +  def _model_() eval(name_singularize.camelize);end
+  def instance_get(sym)     instance_variable_get("@#{sym}"); end
+  def instance_set(sym,obj) instance_variable_set("@#{sym}", obj); end
+  def _model_() eval(name_singularize.camelize);end

この３つのメソッドは public メソッドとして定義されているのは、かなり違和感がありますね 🤔

2018-06-05 08:07 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +  def _model_() eval(name_singularize.camelize);end
ruby のメソッドは小文字始まりの単語を `_` でつなぐスネークケースが一般的です。

2018-06-05 08:07 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +    if obj.class == User
MasterController なのに、 User と出てくるのもかなり違和感ですね 🤔

2018-06-06 04:02 UTC, kawa-mon commented on .gitignore
> +.idea
すみません、.gitignore_globalというのはどこにあるのでしょうか・・？

2018-06-06 04:02 UTC, kawa-mon commented on app/controllers/master_controller.rb
> +class MasterController < ApplicationController
>若干のオーバースペックさを持っているコードになっていないかが心配ですね。
そうですね…
実装の参考ですが、知人のエンジニアからこのような実装方法を聞いたので
腕試しも兼ねてこのようにしてみました。
この後も、Interviewくらいしかビューがないとのことなので
普通にUserController < ApplicationController
の軽症の方がやはり良いでしょうか？

2018-06-06 04:02 UTC, kawa-mon commented on app/controllers/master_controller.rb
> +  def _model_() eval(name_singularize.camelize);end
>この３つのメソッドは public メソッドとして定義されているのは、かなり違和感がありますね 
すみません、これはどういう意味を指されているのでしょうか・・？
やはりオーバースペックということでしょうか？

2018-06-06 04:02 UTC, kawa-mon commented on app/controllers/master_controller.rb
> +    if obj.class == User
おっしゃる通りなのですよね…
上記の通り知人から聞いて試してみただけなのでツギハギのようになってしまいました。。

2018-06-06 05:19 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +class MasterController < ApplicationController
> 腕試しも兼ねてこのようにしてみました。

設計は意図を持ってやるべきだと思うので、この理由ならやめたほうが良いと思いました！
適材適所で使える場面があるはずなので、設計のメリット/デメリットを考慮して選択できるようになる方が良いと思います！

なので、今回の場合でしたら **今の段階では** ApplicationController を継承した UsersController として、実装した方が良いかと思います。
こーゆー複数箇所に書かれるものを Base として共通化するというのは、一旦継承先のクラスを実装したあとに共通化できるところだけ抽出するという方がやりやすいと思いますよ！

2018-06-06 05:21 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +  def _model_() eval(name_singularize.camelize);end
そうですね。
オーバースペックという気持ちがあります。

Controller はあくまで、 View と Model の架け渡しが仕事だと思うので、まずは最低限ここをやることを実装して、あとから必要に応じて追加というのが良さそうに思いました 🙏

2018-06-06 05:23 UTC, pokotyamu commented on app/controllers/master_controller.rb
> +    if obj.class == User
> 上記の通り知人から聞いて試してみただけなのでツギハギのようになってしまいました。。

Qiita やブログ記事を参考にされるのは大いに良いと思います！
ただ、それに対して説明を求められた時に、自分はこういう意図で(メリットがあるので)実装しました！と言える実装になっていれば良いと思いますよ 😄

2018-06-06 15:14 UTC, shingoKawashim commented on app/controllers/master_controller.rb
> +class MasterController < ApplicationController
現段階ではUserController < ApplicationControllerの継承として修正いたしました。
ご確認をお願いいたします。

2018-06-06 15:15 UTC, shingoKawashim commented
現段階ではUserController < ApplicationControllerの継承として修正いたしました。
ご確認をお願いいたします。

2018-06-08 01:19 UTC, pokotyamu commented on .gitignore
> +.idea
> .gitignore_globalという

`.gitignore_global` はホームディレクトリに作るものですね 👍 

以下を参考にしてみてください！
[gitignore_globalとgitignoreを使い分ける - エンジニアはこわくない](http://tsujitaku50.hatenablog.com/entry/2017/01/07/170129)

2018-06-08 01:26 UTC, pokotyamu commented
git の使い方的な話。
--

ブランチ名に `development_kawashima` という名前を使っていますが、ここにはプルリクエストのタイトルと同様に何をそのブランチでしたかったのか？を書くのが良いです！
プルリクエストのタイトルの英訳でもいいので次から意識してみてください！

同じく、コミットメッセージも `no message` など、そのコミットで何がしたかったのかわからないコミットが見受けられますね 👀 
ここもそのコミットで何がしたかった？みたいなことを意識して書いてみると良いと思いますよ 👍

2018-06-08 02:25 UTC, pokotyamu requested changes
@shingoKawashim 設計方針的に気になった点についてコメントしたのでご確認ください 🙏

2018-06-08 02:25 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +  before_action :set_user,               only: [        :edit, :update, :destroy]
```
before_action :require_user_logged_in, only: [:index, :edit, :update, :destroy]
before_action :correct_user,           only: [        :edit, :update, :destroy]
before_action :set_user,               only: [        :edit, :update, :destroy]
```

only のあとの空白はあまり一般的ではないかも。
横に長くなってしまうので、実装が増えた時に見にくくなってしまう気がします 👀

2018-06-08 02:25 UTC, pokotyamu commented on app/controllers/sessions_controller.rb
> +end
実装としては良さそうなんですが、 devise などの gem を使って実装するというのも一つの選択肢としてあった気がしますね 👍 
イチから全部実装するのも良いと思います！

2018-06-08 02:25 UTC, pokotyamu commented on app/assets/javascripts/application.js
> +//= require bootstrap-sprockets
ちょこちょこファイルの最後に改行が入ってないコードがありますね 👀 

[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2018-06-08 02:25 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    end
自分自身かどうかを調べているの良さそう 👍

2018-06-08 02:25 UTC, pokotyamu commented on db/schema.rb
> +    t.integer "deleted", default: 0, null: false, comment: "削除フラグ(0=>未削除,1=>削除)"
この削除フラグって何のために使っているんですか？ 🤔

2018-06-08 02:25 UTC, pokotyamu commented on app/decorators/user_decorator.rb
> +class UserDecorator < Draper::Decorator
Decorator 使った実装初めて見たので、質問なんですが、これを導入すると何が良くなるんですか？ 🙏 
教えていただけると嬉しいです 🙏

2018-06-08 02:25 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    @users = User.alive_records.page(params[:page]).per(10)
ページネーションもいいですね 👍

2018-06-08 02:25 UTC, pokotyamu commented on app/models/application_record.rb
> +    end
`#alive_records` の実装はここにあったのか 👀

2018-06-08 02:25 UTC, pokotyamu commented on app/models/application_record.rb
> +  end
あれ？これひょっとして、削除動作をしても消えずにレコードとしては残り続けます？ 🤔

2018-06-08 02:25 UTC, pokotyamu commented on app/models/application_record.rb
> +    def _deleted_()   1; end
`def _xxx_` で定数定義をしている実装をされていると思うのですが、これって何か参考にされていますか？ 🤔

2018-06-08 02:25 UTC, pokotyamu commented on app/models/application_record.rb
> +    end
うーん。 gem かと思ったら独自実装なのか。。。
あまり一般的ではない独自実装は、逆に他の人からしたらコードの可読性を落とす気がしますね 😓 
普通に `User.where(deleted: _alive_)` と書かれていたほうがまだ読めるなと。

2018-06-08 04:22 UTC, kawa-mon commented
ブランチ名ありがとうございます。
次回から命名していきます！
返答いたします。

2018-06-08 04:23 UTC, kawa-mon commented on app/controllers/users_controller.rb
> +  before_action :set_user,               only: [        :edit, :update, :destroy]
どのCRUDに対して効いているか上下でわかりやすくしたかったのですが、
かえって可読性落としていましたでしょうか^^;？

2018-06-08 04:23 UTC, kawa-mon commented on app/assets/javascripts/application.js
> +//= require bootstrap-sprockets
確かにそうですね、追加します！

2018-06-08 04:26 UTC, kawa-mon commented on db/schema.rb
> +    t.integer "deleted", default: 0, null: false, comment: "削除フラグ(0=>未削除,1=>削除)"
以前、遊び感覚で社内ブログサービスを作って触ってもらったのですが、
誤ってアカウント削除されてしまったことがあり
復旧したい要望をもらってもレコード自体消えてしまって無理だったので
以降ヒューマンエラーを防ぐためこのような実装を心がけています。
再発してもコンソールでフラグを変えてあげれば良いので。

2018-06-08 04:29 UTC, shingoKawashim commented on app/decorators/user_decorator.rb
> +class UserDecorator < Draper::Decorator
各モデルに紐づくview用のロジックをモデルごとに管理できるので、
管理しやすいですしviewも肥大化しないのが良い点だと思っています。

例：https://shgam.hatenadiary.jp/entry/2014/09/17/194633

2018-06-08 04:31 UTC, shingoKawashim commented on app/models/application_record.rb
> +    end
確かにそれもありですね！
User.where(deleted: 0)でも良い気がしてきました。

2018-06-08 04:31 UTC, shingoKawashim commented on app/models/application_record.rb
> +  end
残りますね。

2018-06-08 04:33 UTC, shingoKawashim commented on app/models/application_record.rb
> +    def _deleted_()   1; end
いいえ、特には。
レコードのフラグに関する部分の定数・変数は
_●●_() で書いて区別していました。
あまり意味はないです^^;

2018-06-08 04:35 UTC, shingoKawashim commented on .gitignore
> +.idea
ありがとうございます！やってみます！

2018-06-08 09:17 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +  before_action :set_user,               only: [        :edit, :update, :destroy]
> どのCRUDに対して効いているか上下でわかりやすくしたかった

まだ１行に収まっているから良いんですが、例えば
２行にまたがったり、ずっと空白が出てくるのは読みにくいかなと思いました。

2018-06-08 09:21 UTC, pokotyamu commented on app/models/application_record.rb
> +    def _deleted_()   1; end
定数は基本的に大文字で定義するのが普通ですね！
[変数と定数 (Ruby 2.5.0)](https://docs.ruby-lang.org/ja/latest/doc/spec=2fvariables.html)

2018-06-09 00:19 UTC, kawa-mon commented on .gitignore
> +.idea
設定できました！

2018-06-09 00:19 UTC, shingoKawashim commented on app/controllers/users_controller.rb
> +  before_action :set_user,               only: [        :edit, :update, :destroy]
修正しました！

2018-06-09 00:19 UTC, shingoKawashim commented on app/models/application_record.rb
> +    def _deleted_()   1; end
この場合メソッド名になるので各々
unavailable(), available,(), alive(), deleted()の方が適切でしょうか？

2018-06-11 07:55 UTC, pokotyamu commented on app/models/application_record.rb
> +    def _deleted_()   1; end
Ruby の慣習的には、引数なしのメソッドでは、`()` はいらないですね 😓 
あと、結果として True/False を返すものならば、 boolean 型で定義すべきだと思いました！

2018-06-11 07:56 UTC, pokotyamu commented on app/models/application_record.rb
> +    def _deleted_()   1; end
生きているレコードかどうか以外の情報があるのでしたら、 Integer でも良いかと思うのですが、２値で管理されるものなら boolean 型で良いかなと思います。

2018-06-11 08:09 UTC, pokotyamu commented on app/models/application_record.rb
> +    def _deleted_()   1; end
そして、メソッドと言っても 0 を返す1 を返すということしか管理しないので、これは **定数** ですね。
XXX.deleted の値が作用してなにか値を返すというものでもないですし 😓

2018-06-11 13:24 UTC, shingoKawashim commented
alive_recordsの部分を定数処理に変えてました！
その他の部分もご確認をお願いいたします。

2018-06-12 07:14 UTC, pokotyamu commented
良さそう 👌 
色々突っ込んで話しましたがそれぞれしっかり反応していただきありがとうございました 🙏 
LGTMです 🎉 
マージして次に進んでください！

2018-06-12 09:08 UTC, merged