Interview crud
shingoKawashim/e-navigator pull request #2
Opened 2018-06-15 01:52 UTC by shingoKawashim

やりたかったこと
---

- 自分の面談日時の作成、更新、削除、一覧表示
...

やったこと
----

- ログインユーザーの面談日時だけ処理できるようにrouteをネスト
- 自分以外のユーザーの面談日時は更新、削除出来ないように保護
- ログインユーザー以外は面談日時を作成出来ないように保護
- 後編第2章のためにinterviewsテーブルにはステータスフラグと
　承認でFIXした面談相手が分かるようにmentor_id(承認したuser_id)を入れるための箱を用意
...

動作確認方法
---

- ログインしてサイドバーに出る面談一覧と作成のリンクで確認★
https://e-navigator-shingokawashim.herokuapp.com/

...

その他
---
★heroku run rails db:migrate
でinterviewsテーブルがないので削除できないとのエラーが出てしまいました。

migrationの履歴としては
20180614091226_create_interviews.rbがはじめで確かにdrop_table :interviews
から始まるのでエラーになります。

ローカルでは問題なく動いているのですが、
rails g model Interviewで生成しmigrateした後、rails g destroy Interviewをしたため
最初のcreateしたマイグレーションファイルを削除してしまいました。
ローカルはこれでも履歴が成り立つのですが
heroku上では最初にcreateしたマイグレーションファイルがないためエラーになっているものと考えています。

すでにこのブランチをコミットしてpushもしてしまっているのですが、
マイグレーションファイルを削除してcreateだけのファイルにすれば解消できるのでしょうか？

2018-06-15 05:11 UTC, shingoKawashim commented
heroku rake db:schema:load RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1

で正値のschemaを読み直すことでheroku上も正常動作できました。
データを飛ばさざるを得なかったですが、実際に提供しているWEBサービスの場合
どう対処するのがベストだったでしょうか？

2018-06-18 02:57 UTC, pokotyamu commented
👀

2018-06-18 03:14 UTC, pokotyamu commented
> 20180614091226_create_interviews.rbがはじめで確かにdrop_table :interviews


そもそもこの drop_table って必要なんですっけ？ 🤔 
初めて作るテーブルなはずなので、不要な気がするのですが。

2018-06-18 03:21 UTC, pokotyamu commented
面接の単体での表示は不要と判断したという認識であってますか？ (`#show` がないので)

2018-06-18 03:21 UTC, pokotyamu requested changes
コメント付けました 🙋‍♂️

2018-06-18 03:21 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  before_action :require_user_logged_in, only: [:index, :edit, :update, :destroy]
ここ only で指定しても良いんですが、ログイン系の処理は基本的に全エンドポイントでチェックして欲しいはずなんで、拡張性を考えると only 指定なくても良いかもしれませんね 👀

2018-06-18 03:21 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  before_action :correct_user, only: [:edit, :update, :destroy]
create に関しては、同一ユーザーのチェックしてないのには意図あります？ 🤔

2018-06-18 03:21 UTC, pokotyamu commented on app/models/application_record.rb
> +      where(deleted: 0)
結局定数化止めちゃったんですね 😓 
マジックナンバーを使うのは良くないと思います。

[[実装編]マジック・ナンバーを使ってはいけない | 日経 xTECH（クロステック）](https://tech.nikkeibp.co.jp/it/article/COLUMN/20070820/279836/?rt=nocnt)

2018-06-18 03:21 UTC, pokotyamu commented on config/locales/models/ja.yml
> +        approval: 承認
ここも前回指摘した、ファイル最後の改行が入ってないですね。
エディタ側で保存時に自動的に改行が入るような仕組みを入れておくと良いと思いました！
改行、行末のいらない半角スペースは削除するようにしてみましょう！

2018-06-18 03:21 UTC, pokotyamu commented on config/locales/views/ja.yml
> +      index: "あなたの面談日一覧"
前回指摘できてなかったな 👀 
index という翻訳に対して、 `あなたの` と `他ユーザーの` という２つの表現が一つのプログラムで混在してますね。
`my_index` とか `other_index` ぐらいの具体性を出したほうが良いんじゃないかな？と思いました。

2018-06-18 03:21 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview.all_destroy
ここ、細かいですが、削除が例外なく終了した場合に flash に値をセットするほうが良いですね。
DB の異常などで、削除処理に失敗したときも `削除いたしました` の flash がセットされる気がします。

2018-06-18 03:21 UTC, pokotyamu commented on app/decorators/interview_decorator.rb
> +          model.human_attribute_name(:status),
インデントが空白 4つ分になってる？
よく見たら、 UserDecorator の方も 4つになっている気がします。

2018-06-18 04:45 UTC, shingoKawashim commented
> そもそもこの drop_table って必要なんですっけ？
当時createしようとしたら already existと出たのでdropしました。
createしたマイグレーションファイルをその手前でrails g destroyしてしまったのだと思いますが。

> 面接の単体での表示は不要と判断したという認識であってますか？
あっています。

2018-06-18 04:46 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +  before_action :require_user_logged_in, only: [:index, :edit, :update, :destroy]
確かにそうですね！後で直します！

2018-06-18 04:46 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +  before_action :correct_user, only: [:edit, :update, :destroy]
いや、、ただの漏れですね。。後で直します！

2018-06-18 04:47 UTC, shingoKawashim commented on app/models/application_record.rb
> +      where(deleted: 0)
結局シンプルにすればこうなのでは？と思ったのですが
作った本人だけに通じる「マジックナンバー」という概念があったのですね。。

2018-06-18 04:48 UTC, shingoKawashim commented on config/locales/models/ja.yml
> +        approval: 承認
なるほど！便利な機能ですね！探してみます！

2018-06-18 04:48 UTC, shingoKawashim commented on config/locales/views/ja.yml
> +      index: "あなたの面談日一覧"
確かにそうですね！後で直します！

2018-06-18 04:48 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +    @interview.all_destroy
ここも後で直します！

2018-06-18 04:48 UTC, shingoKawashim commented on app/decorators/interview_decorator.rb
> +          model.human_attribute_name(:status),
直します！

2018-06-20 01:58 UTC, pokotyamu commented
> 当時createしようとしたら already existと出たのでdropしました。
createしたマイグレーションファイルをその手前でrails g destroyしてしまったのだと思いますが。

🤔 
`rails g destroy` ってコマンド叩いたんですか？

2018-06-20 01:59 UTC, pokotyamu commented on config/locales/models/ja.yml
> +        approval: 承認
どんなのを参考にしてみたか教えてもらってもいいですか？ 😄

2018-06-20 02:00 UTC, pokotyamu commented on app/models/application_record.rb
> +      where(deleted: 0)
> 作った本人だけに通じる「マジックナンバー」という概念があったのですね。。

ですね。
あと、0 という数字に対して意味をもたせるというのも定数化においては非常に重要になってきます。
今後生きているレコードという状態を0以外で表現したくなった際、これだとあらゆる箇所を変更しなければならなくなりますが、定数化しておくことで、修正箇所を一つに絞ることも期待できます。

2018-06-20 02:05 UTC, shingoKawashim commented on config/locales/models/ja.yml
> +        approval: 承認
Rubymineを使っているのでこちらを参考にしました！

・最終行追加https://qiita.com/tmknom/items/0704f48f354c703b2dd2#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E4%BF%9D%E5%AD%98%E6%99%82%E3%81%AB%E6%9C%80%E5%BE%8C%E3%81%AE%E8%A1%8C%E3%81%AB%E6%94%B9%E8%A1%8C%E8%BF%BD%E5%8A%A0

・インデント調節
https://qiita.com/iwaseasahi/items/62ad9b8d5bed57e663ed#%E4%BE%8B%E3%81%A8%E3%81%97%E3%81%A6ruby%E3%82%92%E9%81%B8%E6%8A%9E%E3%81%97%E3%81%BE%E3%81%99

・半角、全角スペース明示
http://yucatio.hatenablog.com/entry/2017/02/07/203349

2018-06-20 02:07 UTC, shingoKawashim commented on app/models/application_record.rb
> +      where(deleted: 0)
なるほど！！確かに確かに。ただの数字だと僕しかわからないですよね。
可読性すこぶる悪くて申し訳ございません。。。

2018-06-20 02:08 UTC, shingoKawashim commented
> rails g destroy ってコマンド叩いたんですか？

そうです。

2018-06-20 02:22 UTC, pokotyamu reviewed
動作的には大丈夫だと思いました 👌 
細かい部分直すかどうかおまかせします！

修正した際は再度レビューしますので、依頼を投げてください！よろしくお願いいたします！

2018-06-20 02:22 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      redirect_to user_interviews_path(user_id: current_user.id)
ちなみにですが、 redirect_to のオプションで flash を渡せるので、ここ一行で書くことも出来るはずです。
[redirect_to - リファレンス - - Railsドキュメント](http://railsdoc.com/references/redirect_to)

2018-06-20 02:22 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
特に修正する必要ないですが、これは、条件式を追加しただけで、例外処理を追加したわけではないと思います 👀 
rescue などを使って発生するエラーに対して何かをするというのが例外処理ですね。
(コミットメッセージの話です)

2018-06-20 02:22 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      redirect_to user_interviews_path(user_id: current_user.id)
そして、 flash メッセージは I18n 対応するわけではないんですね 😅 
今回の課題の範囲ではないので、対応しなくても大丈夫ですが。

2018-06-20 03:21 UTC, pokotyamu commented on config/locales/models/ja.yml
> +        approval: 承認
👍 👍 👍 👍

2018-06-20 03:24 UTC, pokotyamu commented
`$ rails g destroy` ってコマンドなくないですか？ 🤔 

```
$ bundle exec rails g --help
Running via Spring preloader in process 7703
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  assets
  channel
  controller
  decorator
  generator
  helper
  integration_test
  jbuilder
  job
  mailer
  migration
  model
  resource
  scaffold
  scaffold_controller
  system_test
  task

Coffee:
  coffee:assets

Draper:
  draper:install

Js:
  js:assets

Kaminari:
  kaminari:config
  kaminari:views

Rspec:
  rspec:decorator

TestUnit:
  test_unit:controller
  test_unit:decorator
  test_unit:generator
  test_unit:helper
  test_unit:integration
  test_unit:job
  test_unit:mailer
  test_unit:model
  test_unit:plugin
  test_unit:scaffold
  test_unit:system

```

2018-06-20 05:16 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +      redirect_to user_interviews_path(user_id: current_user.id)
修正しました！

2018-06-20 05:27 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +    end
そういうことでしたか。
destroyで例外が発生するのはインスタンスがnilの場合くらいでしょうか？
通常動作でこういうことは起きるのでしょうか？
https://qiita.com/jnchito/items/3393c5c1a744199e128a

2018-06-20 05:28 UTC, shingoKawashim commented
あ、すみません！
`rails destroy migration 〜〜`でした。

2018-06-20 07:00 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
そうですね、 nil の場合だったり、 DB へのアクセスができない場合なども本番のアプリケーションだったら考える要素ではあります。
ただ、今回は `#destroy!` ではなく `#destroy` を使っているので、問題ないかと思いました！

2018-06-21 05:44 UTC, merged