後編第ニ章：面接官が面談日程を承認 or 拒否するための機能
shingoKawashim/e-navigator pull request #3
Opened 2018-06-26 15:07 UTC by shingoKawashim

プルリクエストを作成するにあたって、説明文を書いてみましょう。
各項目に例を載せているので、それに合わせて書いてみて下さい！

やりたかったこと
---

- ユーザー登録フォームに生徒/面接官フラグを追加
- 生徒/面接官に応じてサイドバーの表示切り替え
- 生徒の場合、他ユーザーの面談日時は見れない
- 面接官の場合、他ユーザーの面談日時が見れる
- 面接官の場合、他ユーザーの面談日時を承認/却下できる
- 面接官が承認した場合、他の面談日時は却下になる
- 面接官が承認した場合、面談一覧に承認日時を表示

やったこと
----

- ユーザー登録フォームにuser_typeフラグを追加
- user_typeに応じてサイドバーの表示切り替え
- user_typeに応じてuser#indexの表示切り替え
- 面接官用のapproval/rejectアクション
- seedでテストデータ登録

動作確認方法
---

- [ ] アカウント新規作成：user_typeは面接官で
- [ ] ユーザー一覧の川島慎悟のアカウント面談一覧ボタンをクリック
- [ ] どれかの面談を承認
- [ ] 承認・却下のステータスを確認
- [ ] 表示された承認日時を確認

その他
---

2018-06-26 15:10 UTC, shingoKawashim commented
ご確認お願いします。
https://e-navigator-shingokawashim.herokuapp.com/

2018-06-29 02:27 UTC, pokotyamu requested changes
遅くなりましたが、コメント書きました 👍

2018-06-29 02:27 UTC, pokotyamu commented on Gemfile
> +end
32行目に開発とテスト環境用のグループがあるので、そっちにまとめてしまったほうが良いと思いました！

2018-06-29 02:27 UTC, pokotyamu commented on Gemfile
> +end
デバッグしやすくなる仕組みを入れるの良いと思います 👍

2018-06-29 02:27 UTC, pokotyamu commented on app/models/interview.rb
> +      alive_records.where("start_date >= ?", Date.today).order(id: :asc)
ちなみに、これってなんで id の昇順にしてるんですか？ 🤔

2018-06-29 02:27 UTC, pokotyamu commented on app/models/user.rb
> +      return "<span class='badge badge-danger'>面接官</span>".html_safe
View の `ロジック` が Model 層に来てるね 👀 
これは良くないと思います。
`User#user_type` で状態が取れるようになっているので、 View 側に同等のロジックを追加するほうが良いです！

2018-06-29 02:27 UTC, pokotyamu commented on app/models/user.rb
> +    def student_user() {name: "生徒", id: "student" } ;end
すごく細かいけど書き方的な指摘

- ハッシュの書き方統一しましょう！空白の入れ方は前後に１つ。
- もし１行で書きたいなら `;` の前に空白は不要、後ろの空白は必要
- ただ、普通はよっぽどの理由がない限り３行で書くかな。クラス定義ぐらいな印象。

もし自分が書くなら

`def student_user() { name: "生徒", id: "student" }; end`

よりも

```
def student_user 
  { name: '生徒', id: 'student' }
end
```

2018-06-29 02:27 UTC, pokotyamu commented on app/models/user.rb
> +  has_many :interviews, dependent: :destroy
dependent の定義良いですね 👍

2018-06-29 02:27 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    mentor = User.find(@current_user.id)
うーーーん 🤔 
ここの変数定義軍団は不要な感じがするなぁ。
あえて変数に代入している理由ってあります？ 🤔

2018-06-29 02:27 UTC, pokotyamu commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
ちなみになんで enum 使って定義しているんですか？ 😄 
変数定義軍団のリファクタはここらへんを知っているとうまく行けそうな気がします！

2018-06-29 02:27 UTC, pokotyamu commented on app/models/user.rb
> +    def student_user() {name: "生徒", id: "student" } ;end
ちなみに `"` と `'` の違いってご存知ですか？

2018-06-29 02:27 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    mentor = User.find(@current_user.id)
特に `alive` とか `approval` とか `reject` みたいな定数はマジックナンバーになってないですかね？ 👀

2018-06-29 02:27 UTC, pokotyamu commented on db/seeds.rb
> +end
わりと引数が長くなった時は改行含む感じで書くときれいになりますよ。

```
10.times do |number|
  User.create(
    name: "テスト#{number}",
    birthday: "1990-01-01",
    sex: 0,
    school: "テスト#{number}",
    email: "test_#{number}@gmail.com",
    password: "123",
    user_type: 0
  )
end
```

2018-07-01 07:15 UTC, shingoKawashim commented on Gemfile
> +end
たしかにそうですね、整理します！

2018-07-01 07:16 UTC, shingoKawashim commented on app/models/interview.rb
> +      alive_records.where("start_date >= ?", Date.today).order(id: :asc)
作成順にした方が自分で作った通りに並ぶのでわかりやすいかなと。

2018-07-01 07:25 UTC, kawa-mon commented on app/models/user.rb
> +      return "<span class='badge badge-danger'>面接官</span>".html_safe
なるほど！もっとrailsはじめてのころはなんでもviewに突っ込んでいて
それはだめだと知ったのでmodelに突っ込むようにしたのですが、
modelというのはDBへの問い合わせ系ロジックだけをに極力するのがマナーなんですね！

decorator層に移しました！

2018-07-01 07:26 UTC, kawa-mon commented on app/models/user.rb
> +      return "<span class='badge badge-danger'>面接官</span>".html_safe
ちなみに質問なのですが
if文の戻りでreturnを明記しているのですが
これはあったほうが良いのでしょうか？
それともくどいのでやめたほうが良いマナーなのでしょうか？

2018-07-01 07:30 UTC, shingoKawashim commented on app/models/user.rb
> +    def student_user() {name: "生徒", id: "student" } ;end
おーなるほど！勉強になります！

2018-07-01 07:30 UTC, shingoKawashim commented on app/models/user.rb
> +    def student_user() {name: "生徒", id: "student" } ;end
式展開できるのがダブルクォーテーション、できないのがシングルクォーテーション
というのは知っています。

2018-07-01 07:32 UTC, shingoKawashim commented on app/models/user.rb
> +    def student_user() {name: "生徒", id: "student" } ;end
調べたら処理がシングルクォーテーションの方が早いとありました！

式展開の必要がない限りはシングルクォーテーションを用いる、
というのがマナーなのでしょうか？

2018-07-01 08:01 UTC, shingoKawashim commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
reject = 1
interview.update(status: reject)

などは

interview.update(status: :reject)
と書けるのですね！知らなかったです！

2018-07-01 08:01 UTC, shingoKawashim commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
enum使っていたのにもったいない・・・

2018-07-01 08:02 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +    mentor = User.find(@current_user.id)
修正はしましたが、マジックナンバーとは
0とか1とか本人しか分からない表現を避け変数で扱いましょう
という概念だと思っていたのですが違いましたか？^^;

2018-07-01 08:05 UTC, shingoKawashim commented
修正しました！ご確認お願いします！

2018-07-03 07:17 UTC, pokotyamu commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
ヘルパーメソッドについてもう少し調べてほしかったので補足しますね！

```
> interview.reject!
#=> reject 状態にする。
> interview.reject?
#=> reject 状態か判断する。 reject 状態なら true
```

こんな感じで書くことも出来るのがヘルパーメソッドのいいところだと思いました！

2018-07-03 07:23 UTC, pokotyamu commented on app/models/interview.rb
> +      alive_records.where("start_date >= ?", Date.today).order(id: :asc)
なるほど！それも一つですね 👍 
表示の仕方なので、修正しなくてもなんですが
日付順の方が一覧しやすくて良いんだろうなぁと思いました 😄

2018-07-03 07:42 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    other_alive_interviews = Interview.alive_records.where("user_id = (?) AND id != (?)", params[:user_id], params[:id])
なるべく、 生SQLは使わないようにした方がいいかと 👀 

```
Interview.alive_records.where("user_id: params[:user_id]).where.not(id: params[:id]))
```

とかかなぁ 🤔

2018-07-03 07:42 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    other_alive_interviews = Interview.alive_records.where("user_id = (?) AND id != (?)", params[:user_id], params[:id])
そもそも他のレコードにまたがる更新とかのロジック(update_all とか)を Controller 層に書いちゃうのは結構怪しい気もしつつ。今はこのままでいいと思います。
フィードバック面談の時に伝えますね 🙏

2018-07-03 07:42 UTC, pokotyamu commented on app/decorators/interview_decorator.rb
> +  end
自分だったらこう書くかな

```
 def mentor_name
   User.find(mentor_id).name if mentor_id
end
```

return は省略する。 if/unless はまとめれるなら後置で書くとかがコーディングスタンダードな気がします。
あと nil? はあまり使わないかも。

2018-07-03 07:42 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    mentor = User.find(@current_user.id)
あ、すみません指摘間違えてました 🙏 

> 0とか1とか本人しか分からない表現を避け変数で扱いましょう

たしかにおっしゃるとおりですね 🙏 
その内容で合っています！

2018-07-03 07:43 UTC, pokotyamu approved these changes
修正内容確認しました！
動作的にも良さそうに思いますので、マージして次に進んでください 👍

2018-07-03 08:09 UTC, shingoKawashim commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
非破壊的メソッドも使えるのですね！
そこまで調べられませんでした、、ありがとうございます！

2018-07-03 08:10 UTC, shingoKawashim commented on app/controllers/interviews_controller.rb
> +    other_alive_interviews = Interview.alive_records.where("user_id = (?) AND id != (?)", params[:user_id], params[:id])
はい！

2018-07-03 08:10 UTC, shingoKawashim commented on app/decorators/interview_decorator.rb
> +  end
やはり省略で良いのですね。
なるほど！確かにすっきりです。

2018-07-03 08:10 UTC, shingoKawashim commented
ご確認ありがとうございます！進みます！

2018-07-03 08:13 UTC, shingoKawashim commented on app/models/user.rb
> +  enum user_type: { student: 0, mentor: 1 }
確かに英語で探ればありました！
http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

2018-07-04 03:32 UTC, merged