面談日程を知らせるためのメール送信機能
shingoKawashim/e-navigator pull request #4
Opened 2018-07-06 16:19 UTC by shingoKawashim

やりたかったこと
---

- 生徒ログイン時の面談日一覧画面だけに申請先面接官指定欄を表示
- 申請時に生徒・面接官両方にメール送信
- 面接官ログイン時の面談承認時に生徒・面接官両方にメール送信
- gmailから送信

やったこと
----

- 生徒ログイン時の面談日一覧画面だけに申請先面接官指定欄を表示
　use_mentorsというscopeを定義
- InterviewRequestMailerとInterviewApprovalMailerでメール送信
　ローカルではletter_openerでデバッグ
- dotenvと.envファイルでgmailのメアド・パスワードを環境変数に設定

動作確認方法
---

- [ ] 生徒アカウントを新規で作成し、面接を作成
- [ ] 面接官に対して申請を行いメールを確認

- [ ] 面接官アカウントを新規で作成し、生徒の面接を閲覧
- [ ] 承認時に届くメールを確認

2018-07-10 01:43 UTC, pokotyamu requested changes
名前つけと、不要な代入があったのが、気になりましたのでコメント付けています！
修正よろしくお願いいたします！

2018-07-10 01:43 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    info = [mentor, current_user]
これってわざわざ配列にしている意味はあるんですか？ 💭 
呼び出し側で配列展開しているようなので、引数２つにしたら良いんじゃないかと思ったんですが 😓

2018-07-10 01:43 UTC, pokotyamu commented on config/routes.rb
> +    post :mailto
`mailto` は何しているかパット見でわかりにくい名前ですね 🤔 
何についてのメールが送られるのか？といった点がわからなくなっているのが原因だと思います。

ただ、このパス名に `mail` を含んでしまった時はメール以外の通知方法に切り替えますよといった際、パスの名前も切り替える必要がありますよね？
なので、申請とかって意味の apply ぐらいでパスの名前はとどめておくのが良いかなと思いました！

2018-07-10 01:43 UTC, pokotyamu commented on app/mailers/interview_approval_mailer.rb
> +  def send_approval_to_student(info)
`InterviewApprovalMailer#send_approval_to_student` か 🤔 
`approval` が重複して登場するのが結構気になる。。。（`request` の部分も同じく）

`InterviewMailer#approval` で良さそうな気がしますね。
その場合 `request` というメソッドが既に Controller では定義されているので、 apply とかにすると良いかと思いました。

また、キーワード引数 to の値として配列を与えると、１通で同時に送れますよ！

2018-07-11 04:02 UTC, shingoKawashim commented on config/routes.rb
> +    post :mailto
修正します！

2018-07-11 04:02 UTC, shingoKawashim commented on app/controllers/users_controller.rb
> +    info = [mentor, current_user]
確かにそうですね！直しました！

2018-07-11 04:03 UTC, shingoKawashim commented on app/mailers/interview_approval_mailer.rb
> +  def send_approval_to_student(info)
命名は変えてみます！
メンター用と生徒用で送るメールの内容が異なるのですが、
それでもキーワード引数をかえることで同時に送れるのですか？

2018-07-11 04:25 UTC, kawa-mon commented
メールを一通で送るところ以外、修正しました！
ご確認よろしくお願いいたします。
https://e-navigator-shingokawashim.herokuapp.com/

2018-07-11 04:56 UTC, pokotyamu commented on app/mailers/interview_approval_mailer.rb
> +  def send_approval_to_student(info)
> また、キーワード引数 to の値として配列を与えると、１通で同時に送れますよ！

もし同時に送るならばという話だったので、メール内容が異なる場合は分けるというので良いと思います 🙏

2018-07-11 10:19 UTC, pokotyamu commented
うん！改めて修正範囲と実装確認しました！
良さそうに思います 👌 

LGTM  です 🎉 

e-Navigator 完走お疲れ様でした！！！！

2018-07-11 15:10 UTC, merged